"""Latency and throughput tracking for pruning experiments.

What we measure per sample:
  - total wall-clock time for one bot.inference() call
  - GPU peak memory during that call
  - Number of visual tokens before pruning (always 576 for HuatuoGPT)
  - Number of visual tokens after pruning (depends on keep_ratio)
  - Number of tokens generated

We deliberately don't try to split prefill vs decode latency in this first
version - that requires hooking forward() and adds complexity. Total wall
clock per sample, aggregated across the benchmark, is enough to compute the
speed/accuracy tradeoff plot we care about.
"""
import time
import torch
from dataclasses import dataclass, asdict
from typing import List, Optional
import json
import os


@dataclass
class SampleLatency:
    sample_id: str
    total_time_s: float
    gpu_peak_mb: float
    n_visual_pre: int       # visual tokens before pruning (always 576 here)
    n_visual_post: int      # visual tokens after pruning
    n_generated: int        # tokens generated by the model


class LatencyTracker:
    """Per-sample latency capture. Use as a context manager around inference."""

    def __init__(self):
        self.records: List[SampleLatency] = []
        # Tracker shared with the patcher to read pruning info during sample
        self._current_visual_pre = 576
        self._current_visual_post = 576

    def set_visual_counts(self, pre: int, post: int):
        """Called by the patcher right after a pruning decision."""
        self._current_visual_pre = pre
        self._current_visual_post = post

    def time_sample(self, sample_id: str, n_generated: Optional[int] = None):
        """Context manager: time one inference call."""
        return _SampleTimer(self, sample_id, n_generated)

    def summary(self):
        """Aggregate stats for printing."""
        if not self.records:
            return {}
        times = [r.total_time_s for r in self.records]
        mems = [r.gpu_peak_mb for r in self.records]
        n_post = [r.n_visual_post for r in self.records]
        return {
            "n_samples": len(self.records),
            "total_time_s": sum(times),
            "mean_time_s": sum(times) / len(times),
            "p50_time_s": sorted(times)[len(times) // 2],
            "p95_time_s": sorted(times)[int(0.95 * len(times))],
            "mean_gpu_peak_mb": sum(mems) / len(mems),
            "mean_visual_post_prune": sum(n_post) / len(n_post),
        }

    def save_jsonl(self, path: str):
        """Save per-sample records as JSON lines."""
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            for r in self.records:
                f.write(json.dumps(asdict(r)) + "\n")


class _SampleTimer:
    """Context manager. Records on __exit__."""

    def __init__(self, tracker: LatencyTracker, sample_id: str, n_generated: Optional[int]):
        self.tracker = tracker
        self.sample_id = sample_id
        self.n_generated = n_generated
        self.t0 = None

    def __enter__(self):
        # Sync to make sure prior GPU work is done before we start timing
        if torch.cuda.is_available():
            torch.cuda.synchronize()
            torch.cuda.reset_peak_memory_stats()
        self.t0 = time.perf_counter()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if torch.cuda.is_available():
            torch.cuda.synchronize()
        elapsed = time.perf_counter() - self.t0
        peak_mb = 0.0
        if torch.cuda.is_available():
            peak_mb = torch.cuda.max_memory_allocated() / (1024 * 1024)
        self.tracker.records.append(SampleLatency(
            sample_id=self.sample_id,
            total_time_s=elapsed,
            gpu_peak_mb=peak_mb,
            n_visual_pre=self.tracker._current_visual_pre,
            n_visual_post=self.tracker._current_visual_post,
            n_generated=self.n_generated if self.n_generated is not None else -1,
        ))
        return False  # don't suppress exceptions

    def set_n_generated(self, n: int):
        self.n_generated = n
